// 06-solid/src/App.jsx
import { For, createSignal, onMount } from 'solid-js'

function App() {
  const [input, setInput] = createSignal('')
  const [users, setUsers] = createSignal([])

  const filteredUsers = () =>
    users().filter((u) => u.name.toLowerCase().includes(input().toLowerCase()))

  onMount(async () => {
    const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
    setUsers(await res.json())
  })

  return (
    <>
      <input type="text" onInput={(e) => setInput(e.target.value)} />
      <ul>
        <For each={filteredUsers()}>{(user) => <li>{user.name}</li>}</For>
      </ul>
    </>
  )
}

export default App

// 02-react/src/App.js
import { useEffect, useRef, useState } from 'react'

function App() {
  const allUsers = useRef([])

  const [users, setUsers] = useState([])
  const [input, setInput] = useState('')

  useEffect(() => {
    async function fetchUsers() {
      const res = await fetch('https://jsonplaceholder.typicode.com/users')
      allUsers.current = await res.json()
      setUsers(allUsers.current)
    }
    fetchUsers()
  }, [])

  useEffect(() => {
    setUsers(
      allUsers.current.filter((u) =>
        u.name.toLowerCase().includes(input.toLowerCase())
      )
    )
  }, [input])

  return (
    <>
      <input value={input} onChange={(e) => setInput(e.target.value)} />

      <ul>
        {users.map((user) => (
          <li key={user.id}>{user.name}</li>
        ))}
      </ul>
    </>
  )
}

export default App
