// 05-svelte/src/App.svelte
<script>
import { onMount } from 'svelte';

let users = [];
let input = '';

$: filteredUsers = users.filter(u => 
	u.name.toLowerCase().includes(input.toLowerCase())
)

onMount(async () => {
	const res = await fetch(`https://jsonplaceholder.typicode.com/users`);
	users = await res.json();
});
</script>

<main>
	<input type="text" bind:value={input}>

	<ul>
		{#each filteredUsers as user}
		<li>{user.name}</li>
		{/each}
	</ul>
</main>

// 06-solid/src/App.jsx
import { For, createSignal, onMount } from 'solid-js'

function App() {
  const [input, setInput] = createSignal('')
  const [users, setUsers] = createSignal([])

  const filteredUsers = () =>
    users().filter((u) => u.name.toLowerCase().includes(input().toLowerCase()))

  onMount(async () => {
    const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
    setUsers(await res.json())
  })

  return (
    <>
      <input type="text" onInput={(e) => setInput(e.target.value)} />
      <ul>
        <For each={filteredUsers()}>{(user) => <li>{user.name}</li>}</For>
      </ul>
    </>
  )
}

export default App
